########################################
#           DEV PRODUCTION             #
########################################

version: "3.3"
services:
  node:
    container_name: civita
    restart: always
    # build: .
    image: node:16.7.0
    ports:
      - "3004:3004"
    # MIT bu yerda martin orniga oziz nomiz kiriting, loyiha nomini ham ozgartiring
    volumes:
      - "/home/martin/civita:/usr/src/applications"


    working_dir: "/usr/src/applications"

    expose:
      - "3004"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # FOR DEVELOPMENT
    command: bash -c "npm install && npm run build && npm run start"

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
